// auto-generated by circomkit
pragma circom 2.1.8;

include "../proto-pod-gpc.circom";

component main {public[entryObjectIndex, entryNameHash, entryIsValueHashRevealed, virtualEntryIsValueHashRevealed, entryEqualToOtherEntryByIndex, entryIsEqualToOtherEntry, ownerExternalNullifier, ownerV3EntryIndex, ownerV3IsNullifierHashRevealed, ownerV4EntryIndex, ownerV4IsNullifierHashRevealed, numericValueEntryIndices, numericValueInRange, numericMinValues, numericMaxValues, entryInequalityValueIndex, entryInequalityOtherValueIndex, entryInequalityIsLessThan, tupleIndices, listComparisonValueIndex, listContainsComparisonValue, listValidValues, requireUniqueContentIDs, globalWatermark]} = ProtoPODGPC(1, 1, 5, 0, 0, 0, 0, 0, 0, 0, 1);
